DROP USER MAX_TEST1 CASCADE;

CREATE USER MAX_TEST1
IDENTIFIED BY MAX_TEST1;

-- grant/revoke system privileges 
GRANT GLOBAL QUERY REWRITE TO MAX_TEST1;
GRANT SELECT ANY TABLE TO MAX_TEST1;
GRANT UNLIMITED TABLESPACE TO MAX_TEST1;

GRANT CREATE TABLE TO MAX_TEST1;
GRANT CREATE SESSION TO MAX_TEST1;
GRANT CREATE PROCEDURE TO MAX_TEST1;
GRANT CREATE TRIGGER TO MAX_TEST1;
GRANT CREATE VIEW TO MAX_TEST1;
GRANT CREATE SEQUENCE TO MAX_TEST1;
GRANT CREATE VIEW TO MAX_TEST1;
GRANT CREATE ROLE TO MAX_TEST1;
GRANT CREATE MATERIALIZED VIEW TO MAX_TEST1;
GRANT CREATE USER TO MAX_TEST1;
--Jobs-------------------
GRANT CREATE JOB TO MAX_TEST1;
--GRANT CREATE ANY JOB TO &1;
GRANT MANAGE SCHEDULER TO MAX_TEST1;
-----------------------

GRANT DELETE ANY TABLE TO MAX_TEST1;
GRANT DROP ANY TABLE TO MAX_TEST1;
GRANT DROP ANY PROCEDURE TO MAX_TEST1;
GRANT DROP ANY TRIGGER TO MAX_TEST1;
GRANT DROP ANY VIEW TO MAX_TEST1;
GRANT DROP ANY ROLE TO MAX_TEST1;
GRANT DROP ANY SYNONYM TO MAX_TEST1;
GRANT DROP USER TO MAX_TEST1;

GRANT ALTER ANY TABLE TO MAX_TEST1;
GRANT ALTER ANY TABLE TO MAX_TEST1;
GRANT ALTER ANY PROCEDURE TO MAX_TEST1;
GRANT ALTER ANY TRIGGER TO MAX_TEST1;
GRANT ALTER USER TO MAX_TEST1;

GRANT AQ_ADMINISTRATOR_ROLE TO MAX_TEST1;
GRANT EXECUTE ON DBMS_AQ TO MAX_TEST1;

GRANT DEBUG CONNECT SESSION TO MAX_TEST1;

GRANT CONNECT TO MAX_TEST1 WITH ADMIN OPTION;
--for allow to register xml schemas
GRANT ALTER SESSION TO MAX_TEST1;

--- test -----
GRANT CREATE INDEXTYPE TO MAX_TEST1;
GRANT CREATE LIBRARY TO MAX_TEST1;
GRANT CREATE OPERATOR TO MAX_TEST1;
GRANT CREATE PUBLIC SYNONYM TO MAX_TEST1;
GRANT CREATE ANY SYNONYM TO MAX_TEST1;
GRANT CREATE TYPE TO MAX_TEST1;
GRANT CREATE VIEW TO MAX_TEST1;
GRANT DROP PUBLIC SYNONYM TO MAX_TEST1;

EXIT SQL.SQLCODE